version: 0.0
os: linux
files:
  - source: /
    destination: /home/user3/ml-app/
    overwrite: true

hooks:
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root