version: 0.0
os: linux
files:
  - source: /
    destination: /home/omar/ml-app/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_aplication.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root