version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10.12
    commands:
      - echo "========= installing dependencies ========="
      - pip install poetry
      - poetry install
  pre_build:
    commands:
      - echo "========= Testing Step ========="
      - poetry run pytest

  build:
    commands:
      - echo "========= Training Model ========="
      - poetry run python ./src/model/training.py