services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python-app
    image: ocastano/python-app
    volumes:
      - .:/app
    ports:
      - 8000:8000

volumes:
  python-app:
    external: false
